export const PRODUCTS_LIST = 'PRODUCTS_LIST';
export const PRODUCT_DETAILS = 'PRODUCT_DETAILS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHANGE_CART_QTY = 'CHANGE_CART_QTY';
export const SEARCH_ACTION = 'SEARCH_ACTION';
